[loss_function]
loss_function_type = "binary_cross_entropy_loss"

[dataset]
root_dir = "/scratch1/skovaka/hct116/uncalled/train_new/dataprep/unc_pri_bam"
min_reads = 20
norm_path = "/scratch1/skovaka/hct116/uncalled/train_new/train_pri_bam/norm_dict_nanopolish.joblib"   
num_neighboring_features = 1

[dataloader]
    [dataloader.train]
    batch_size = 256
    sampler = "ImbalanceOverSampler"

    [dataloader.val]
    batch_size = 256
    shuffle = false

    [dataloader.test]
    batch_size = 256
    shuffle = false
